Feature/search
alsgud8311/domtory_native pull request #9
Opened 2024-02-06 16:07 UTC by Seoheeda

- 검색 페이지 및 검색 결과 목록 layout 및 design 완료했습니다.
- fontawesome 위한 라이브러리 설치했습니다.

2024-02-07 02:06 UTC, alsgud8311 reviewed
Fontawesome 아이콘들 expo-vector-icons에 있을텐데..?

2024-02-07 02:07 UTC, alsgud8311 requested changes
바꿀 수 있음 바꿔주세용

2024-02-07 13:13 UTC, siawase17 approved these changes
Lgtm

2024-02-08 08:03 UTC, alsgud8311 approved these changes

2024-02-08 08:03 UTC, merged